#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.
MSG="Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
if [ $# -eq 0 ];
then
    echo "$MSG"
else
    for ip_add in "$@"; do
        ping -c 5 "$ip_add"
    done
fi
